2024-05-17 14:14:44,701 - INFO - routes.py:1672 - Fetched 334 documents for sensor_id: 01dc8098-5931-4913-8ea5-181d7726dcf5
2024-05-17 14:14:44,703 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01dc8098-5931-4913-8ea5-181d7726dcf5:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:55,205 - INFO - routes.py:1672 - Fetched 8526 documents for sensor_id: 014f8147-ee70-48cb-aa68-ef58e54eaefe
2024-05-17 14:14:55,206 - ERROR - routes.py:1675 - Error fetching data for sensor_id 014f8147-ee70-48cb-aa68-ef58e54eaefe:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:55,419 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 0136cda1-63b7-44dd-99e9-4592ebe441fd
2024-05-17 14:14:55,420 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0136cda1-63b7-44dd-99e9-4592ebe441fd:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:55,516 - INFO - routes.py:1672 - Fetched 8464 documents for sensor_id: 01f33ba2-de83-437a-bd38-b76e2a400e64
2024-05-17 14:14:55,518 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01f33ba2-de83-437a-bd38-b76e2a400e64:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:58,746 - INFO - routes.py:1672 - Fetched 5748 documents for sensor_id: 05ff5916-2293-43da-ab30-a7ed296c76f1
2024-05-17 14:14:58,826 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05ff5916-2293-43da-ab30-a7ed296c76f1:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:58,831 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed
2024-05-17 14:14:58,847 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:58,964 - INFO - routes.py:1672 - Fetched 8530 documents for sensor_id: 022040a0-beb4-413c-bc3b-e6564fc2699c
2024-05-17 14:14:58,965 - ERROR - routes.py:1675 - Error fetching data for sensor_id 022040a0-beb4-413c-bc3b-e6564fc2699c:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:59,459 - INFO - routes.py:1672 - Fetched 8467 documents for sensor_id: 01412db0-c82d-4e90-bd07-261186c7844a
2024-05-17 14:14:59,460 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01412db0-c82d-4e90-bd07-261186c7844a:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:14:59,607 - INFO - routes.py:1672 - Fetched 8474 documents for sensor_id: 0425ff76-ae5e-41e4-8938-858aa06ac969
2024-05-17 14:14:59,627 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0425ff76-ae5e-41e4-8938-858aa06ac969:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:15:00,271 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 05e53979-da58-4f07-90ab-d4dbfcf27929
2024-05-17 14:15:00,272 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05e53979-da58-4f07-90ab-d4dbfcf27929:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:15:00,834 - INFO - routes.py:1672 - Fetched 8031 documents for sensor_id: 0486613b-8ba0-4d73-8bcd-e306514650ad
2024-05-17 14:15:00,835 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0486613b-8ba0-4d73-8bcd-e306514650ad:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:15:01,096 - INFO - routes.py:1672 - Fetched 8504 documents for sensor_id: 0254a9ea-9295-44a8-a2de-adb7055cd3ab
2024-05-17 14:15:01,097 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0254a9ea-9295-44a8-a2de-adb7055cd3ab:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:15:02,183 - INFO - routes.py:1672 - Fetched 8536 documents for sensor_id: 0609d19f-ca0b-420b-a854-3fe0d087b32f
2024-05-17 14:15:02,183 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0609d19f-ca0b-420b-a854-3fe0d087b32f:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:15:03,334 - INFO - routes.py:1672 - Fetched 8433 documents for sensor_id: 06572c33-bf33-4981-9089-c06c2b68abb6
2024-05-17 14:15:03,336 - ERROR - routes.py:1675 - Error fetching data for sensor_id 06572c33-bf33-4981-9089-c06c2b68abb6:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:23,470 - INFO - routes.py:1672 - Fetched 334 documents for sensor_id: 01dc8098-5931-4913-8ea5-181d7726dcf5
2024-05-17 14:29:23,471 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01dc8098-5931-4913-8ea5-181d7726dcf5:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:36,155 - INFO - routes.py:1672 - Fetched 8031 documents for sensor_id: 0486613b-8ba0-4d73-8bcd-e306514650ad
2024-05-17 14:29:36,156 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0486613b-8ba0-4d73-8bcd-e306514650ad:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:36,650 - INFO - routes.py:1672 - Fetched 8464 documents for sensor_id: 01f33ba2-de83-437a-bd38-b76e2a400e64
2024-05-17 14:29:36,651 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01f33ba2-de83-437a-bd38-b76e2a400e64:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:36,897 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 0136cda1-63b7-44dd-99e9-4592ebe441fd
2024-05-17 14:29:36,899 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0136cda1-63b7-44dd-99e9-4592ebe441fd:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:37,788 - INFO - routes.py:1672 - Fetched 8526 documents for sensor_id: 014f8147-ee70-48cb-aa68-ef58e54eaefe
2024-05-17 14:29:37,845 - INFO - routes.py:1672 - Fetched 5748 documents for sensor_id: 05ff5916-2293-43da-ab30-a7ed296c76f1
2024-05-17 14:29:37,846 - ERROR - routes.py:1675 - Error fetching data for sensor_id 014f8147-ee70-48cb-aa68-ef58e54eaefe:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:37,847 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05ff5916-2293-43da-ab30-a7ed296c76f1:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:38,194 - INFO - routes.py:1672 - Fetched 8467 documents for sensor_id: 01412db0-c82d-4e90-bd07-261186c7844a
2024-05-17 14:29:38,195 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01412db0-c82d-4e90-bd07-261186c7844a:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:39,974 - INFO - routes.py:1672 - Fetched 8474 documents for sensor_id: 0425ff76-ae5e-41e4-8938-858aa06ac969
2024-05-17 14:29:39,975 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0425ff76-ae5e-41e4-8938-858aa06ac969:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:42,135 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed
2024-05-17 14:29:42,137 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:42,367 - INFO - routes.py:1672 - Fetched 8530 documents for sensor_id: 022040a0-beb4-413c-bc3b-e6564fc2699c
2024-05-17 14:29:42,368 - ERROR - routes.py:1675 - Error fetching data for sensor_id 022040a0-beb4-413c-bc3b-e6564fc2699c:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:29:42,624 - INFO - routes.py:1672 - Fetched 8471 documents for sensor_id: 05ade6d3-a470-4b25-b4fd-6d88ef28ace5
2024-05-17 14:29:42,626 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05ade6d3-a470-4b25-b4fd-6d88ef28ace5:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:33,725 - INFO - routes.py:1672 - Fetched 334 documents for sensor_id: 01dc8098-5931-4913-8ea5-181d7726dcf5
2024-05-17 14:30:33,727 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01dc8098-5931-4913-8ea5-181d7726dcf5:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:43,461 - INFO - routes.py:1672 - Fetched 8474 documents for sensor_id: 0425ff76-ae5e-41e4-8938-858aa06ac969
2024-05-17 14:30:43,463 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0425ff76-ae5e-41e4-8938-858aa06ac969:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:47,632 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 0136cda1-63b7-44dd-99e9-4592ebe441fd
2024-05-17 14:30:47,633 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0136cda1-63b7-44dd-99e9-4592ebe441fd:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:47,722 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 05e53979-da58-4f07-90ab-d4dbfcf27929
2024-05-17 14:30:47,722 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05e53979-da58-4f07-90ab-d4dbfcf27929:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:48,357 - INFO - routes.py:1672 - Fetched 5748 documents for sensor_id: 05ff5916-2293-43da-ab30-a7ed296c76f1
2024-05-17 14:30:48,358 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05ff5916-2293-43da-ab30-a7ed296c76f1:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:48,739 - INFO - routes.py:1672 - Fetched 8031 documents for sensor_id: 0486613b-8ba0-4d73-8bcd-e306514650ad
2024-05-17 14:30:48,742 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0486613b-8ba0-4d73-8bcd-e306514650ad:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:50,836 - INFO - routes.py:1672 - Fetched 8536 documents for sensor_id: 0609d19f-ca0b-420b-a854-3fe0d087b32f
2024-05-17 14:30:50,837 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0609d19f-ca0b-420b-a854-3fe0d087b32f:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:52,825 - INFO - routes.py:1672 - Fetched 8504 documents for sensor_id: 0254a9ea-9295-44a8-a2de-adb7055cd3ab
2024-05-17 14:30:53,058 - INFO - routes.py:1672 - Fetched 8467 documents for sensor_id: 01412db0-c82d-4e90-bd07-261186c7844a
2024-05-17 14:30:53,063 - INFO - routes.py:1672 - Fetched 8530 documents for sensor_id: 022040a0-beb4-413c-bc3b-e6564fc2699c
2024-05-17 14:30:53,142 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed
2024-05-17 14:30:53,213 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:53,210 - ERROR - routes.py:1675 - Error fetching data for sensor_id 0254a9ea-9295-44a8-a2de-adb7055cd3ab:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:53,212 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01412db0-c82d-4e90-bd07-261186c7844a:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:53,212 - ERROR - routes.py:1675 - Error fetching data for sensor_id 022040a0-beb4-413c-bc3b-e6564fc2699c:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:53,209 - INFO - routes.py:1672 - Fetched 8526 documents for sensor_id: 014f8147-ee70-48cb-aa68-ef58e54eaefe
2024-05-17 14:30:53,302 - ERROR - routes.py:1675 - Error fetching data for sensor_id 014f8147-ee70-48cb-aa68-ef58e54eaefe:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:55,532 - INFO - routes.py:1672 - Fetched 8471 documents for sensor_id: 05ade6d3-a470-4b25-b4fd-6d88ef28ace5
2024-05-17 14:30:55,533 - ERROR - routes.py:1675 - Error fetching data for sensor_id 05ade6d3-a470-4b25-b4fd-6d88ef28ace5:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:57,478 - INFO - routes.py:1672 - Fetched 8553 documents for sensor_id: 069055a1-371f-4854-82fc-08620285fe52
2024-05-17 14:30:57,480 - ERROR - routes.py:1675 - Error fetching data for sensor_id 069055a1-371f-4854-82fc-08620285fe52:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:30:59,389 - INFO - routes.py:1672 - Fetched 8464 documents for sensor_id: 01f33ba2-de83-437a-bd38-b76e2a400e64
2024-05-17 14:30:59,390 - ERROR - routes.py:1675 - Error fetching data for sensor_id 01f33ba2-de83-437a-bd38-b76e2a400e64:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:31:00,542 - INFO - routes.py:1672 - Fetched 8539 documents for sensor_id: 09067b68-7a2a-4bfe-b350-0757b450ea08
2024-05-17 14:31:00,543 - ERROR - routes.py:1675 - Error fetching data for sensor_id 09067b68-7a2a-4bfe-b350-0757b450ea08:
Traceback (most recent call last):
  File "D:\HourlyAPi\HourlyPredApi\routes\routes.py", line 1673, in data_fetch
    return jsonify(results)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IT Radius\anaconda3\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-05-17 14:31:30,766 - INFO - routes.py:1672 - Fetched 334 documents for sensor_id: 01dc8098-5931-4913-8ea5-181d7726dcf5
2024-05-17 14:31:37,170 - INFO - routes.py:1672 - Fetched 5748 documents for sensor_id: 05ff5916-2293-43da-ab30-a7ed296c76f1
2024-05-17 14:31:39,253 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 05e53979-da58-4f07-90ab-d4dbfcf27929
2024-05-17 14:31:42,503 - INFO - routes.py:1672 - Fetched 8526 documents for sensor_id: 014f8147-ee70-48cb-aa68-ef58e54eaefe
2024-05-17 14:31:46,171 - INFO - routes.py:1672 - Fetched 8464 documents for sensor_id: 01f33ba2-de83-437a-bd38-b76e2a400e64
2024-05-17 14:31:46,176 - INFO - routes.py:1672 - Fetched 8474 documents for sensor_id: 0425ff76-ae5e-41e4-8938-858aa06ac969
2024-05-17 14:31:46,594 - INFO - routes.py:1672 - Fetched 8471 documents for sensor_id: 05ade6d3-a470-4b25-b4fd-6d88ef28ace5
2024-05-17 14:31:47,037 - INFO - routes.py:1672 - Fetched 8467 documents for sensor_id: 01412db0-c82d-4e90-bd07-261186c7844a
2024-05-17 14:31:47,041 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 01de48d6-058e-4eb0-8a6b-b9519a3ea4ed
2024-05-17 14:31:48,027 - INFO - routes.py:1672 - Fetched 8530 documents for sensor_id: 022040a0-beb4-413c-bc3b-e6564fc2699c
2024-05-17 14:31:48,350 - INFO - routes.py:1672 - Fetched 8031 documents for sensor_id: 0486613b-8ba0-4d73-8bcd-e306514650ad
2024-05-17 14:31:50,207 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 0136cda1-63b7-44dd-99e9-4592ebe441fd
2024-05-17 14:31:50,729 - INFO - routes.py:1672 - Fetched 8504 documents for sensor_id: 0254a9ea-9295-44a8-a2de-adb7055cd3ab
2024-05-17 14:31:52,703 - INFO - routes.py:1672 - Fetched 8536 documents for sensor_id: 0609d19f-ca0b-420b-a854-3fe0d087b32f
2024-05-17 14:31:52,891 - INFO - routes.py:1672 - Fetched 8543 documents for sensor_id: 06545110-09ac-4e99-8b35-740cbced44e7
2024-05-17 14:31:53,740 - INFO - routes.py:1672 - Fetched 6471 documents for sensor_id: 0915e39b-2ec2-4b88-97c4-ae13ea63aca6
2024-05-17 14:31:57,420 - INFO - routes.py:1672 - Fetched 8433 documents for sensor_id: 06572c33-bf33-4981-9089-c06c2b68abb6
2024-05-17 14:31:57,576 - INFO - routes.py:1672 - Fetched 3 documents for sensor_id: 0c225f6a-dfe7-4f03-a0ef-d44d20abfc6a
2024-05-17 14:32:00,943 - INFO - routes.py:1672 - Fetched 8413 documents for sensor_id: 07617d4d-e6c1-4a59-b454-137a988cf9fa
2024-05-17 14:32:01,615 - INFO - routes.py:1672 - Fetched 8553 documents for sensor_id: 069055a1-371f-4854-82fc-08620285fe52
2024-05-17 14:32:01,780 - INFO - routes.py:1672 - Fetched 8532 documents for sensor_id: 06edb7f2-c8f9-4e28-a823-272c66a1bce3
2024-05-17 14:32:02,156 - INFO - routes.py:1672 - Fetched 0 documents for sensor_id: 0dae0eaa-465f-4d56-a475-de6fe6e09f69
2024-05-17 14:32:03,681 - INFO - routes.py:1672 - Fetched 8431 documents for sensor_id: 0bcf7274-25c4-41ae-85e5-680702137250
2024-05-17 14:32:09,526 - INFO - routes.py:1672 - Fetched 8539 documents for sensor_id: 09067b68-7a2a-4bfe-b350-0757b450ea08
2024-05-17 14:32:10,542 - INFO - routes.py:1672 - Fetched 8509 documents for sensor_id: 09000d79-16f7-4a68-a268-9520006025c1
2024-05-17 14:32:10,788 - INFO - routes.py:1672 - Fetched 8377 documents for sensor_id: 0a9b8add-51bd-4e89-9b33-1459b45b73a3
2024-05-17 14:32:11,001 - INFO - routes.py:1672 - Fetched 5595 documents for sensor_id: 0c970c0b-9295-466e-abda-daf237bc8824
2024-05-17 14:32:11,293 - INFO - routes.py:1672 - Fetched 8538 documents for sensor_id: 0a1a23d1-89c5-4bb2-8654-ee64694e52fb
2024-05-17 14:32:11,370 - INFO - routes.py:1672 - Fetched 8549 documents for sensor_id: 0c9251f7-92b4-4047-a4fe-9b13bf0d951c
2024-05-17 14:32:12,773 - INFO - routes.py:1672 - Fetched 8514 documents for sensor_id: 0ba4db4e-cddc-4867-963f-e02af61760ec
2024-05-17 14:32:12,783 - INFO - routes.py:1672 - Fetched 4274 documents for sensor_id: 0e279544-405e-4d1b-bd6c-f45c65a30922
2024-05-17 14:32:12,864 - INFO - routes.py:1672 - Fetched 8534 documents for sensor_id: 0a890c82-9003-4c3d-a8de-d82ee74e0658
2024-05-17 14:32:12,869 - INFO - routes.py:1672 - Fetched 8558 documents for sensor_id: 09d008e3-88ab-4bf5-b32d-c0fc5047443a
2024-05-17 14:32:17,946 - INFO - routes.py:1672 - Fetched 8420 documents for sensor_id: 102a975e-91cc-4865-bf7e-b8cc7c9f1fc8
2024-05-17 14:32:18,239 - INFO - routes.py:1672 - Fetched 8487 documents for sensor_id: 0f0b03dd-27a5-4e24-b182-da1fa05d47b1
2024-05-17 14:32:19,024 - INFO - routes.py:1672 - Fetched 8555 documents for sensor_id: 0cb518eb-d811-44e6-831b-9c3ab722ea8a
2024-05-17 14:32:19,443 - INFO - routes.py:1672 - Fetched 8425 documents for sensor_id: 10f56c0b-2c35-421a-ae99-d6cc8b85d802
2024-05-17 14:32:21,134 - INFO - routes.py:1672 - Fetched 8543 documents for sensor_id: 0eb052b1-1217-43e0-96d6-b8c57e2233e8
2024-05-17 14:32:22,069 - INFO - routes.py:1672 - Fetched 8349 documents for sensor_id: 0e25f874-14a6-460e-9b25-b9559b51716e
2024-05-17 14:32:22,934 - INFO - routes.py:1672 - Fetched 8423 documents for sensor_id: 0f83276c-7660-46f4-872d-4644b0da446b
2024-05-17 14:32:24,310 - INFO - routes.py:1672 - Fetched 8366 documents for sensor_id: 128d8d2a-ade7-4227-8f6a-206086298b6e
2024-05-17 14:32:24,449 - INFO - routes.py:1672 - Fetched 8547 documents for sensor_id: 13861ee4-fa17-4f22-a45c-b63a4c7a4e56
2024-05-17 14:32:24,459 - INFO - routes.py:1672 - Fetched 8524 documents for sensor_id: 11469090-3dc1-4c91-b9b5-f27e8e146bf1
2024-05-17 14:32:25,248 - INFO - routes.py:1672 - Fetched 8496 documents for sensor_id: 132901a9-dde8-4db2-b5f0-8be12285a147
2024-05-17 14:32:25,885 - INFO - routes.py:1672 - Fetched 8525 documents for sensor_id: 132dc10f-63ae-44d0-a8f7-d21729a32be7
2024-05-17 14:32:26,331 - INFO - routes.py:1672 - Fetched 8528 documents for sensor_id: 12963819-806a-4df1-a7a8-657ad652255c
2024-05-17 14:32:26,424 - INFO - routes.py:1672 - Fetched 8518 documents for sensor_id: 115f469b-1fca-4f9b-98bb-37a814cdc237
2024-05-17 14:32:28,375 - INFO - routes.py:1672 - Fetched 8523 documents for sensor_id: 15213969-e0dd-4a33-b039-39add4907188
2024-05-17 14:32:28,916 - INFO - routes.py:1672 - Fetched 5132 documents for sensor_id: 16cc8139-941e-486f-af1a-7d6967073290
